name: Build and Deploy to Heroku


on:
  push:
    branches:
      - testing # Adjust to the branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'beatmapbrowser'
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          docker_build_args: "SITE_CERT SITE_KEY CLIENT_SECRET BOT_TOKEN DOMAIN"
        env:
          DOMAIN: beatmapbrowser.me
          SITE_CERT: ${{secrets.SITE_CERT}}
          SITE_KEY: ${{secrets.SITE_KEY}}
          BOT_TOKEN: ${{secrets.BOT_TOKEN}}
          CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
